// Default shared exercise database. Seeded once on first run.
module.exports = [
  // Upper
  { name: 'Incline DB Press', category: 'upper', equipment: 'dumbbell' },
  { name: 'Flat Bench Press', category: 'upper', equipment: 'barbell' },
  { name: 'Machine Shoulder Press', category: 'upper', equipment: 'machine' },
  { name: 'Overhead Press', category: 'upper', equipment: 'barbell' },
  { name: 'Lat Pulldown', category: 'upper', equipment: 'cable' },
  { name: 'Pull-ups', category: 'upper', equipment: 'bodyweight' },
  { name: 'Cable Row', category: 'upper', equipment: 'cable' },
  { name: 'Barbell Row', category: 'upper', equipment: 'barbell' },
  { name: 'Bicep Curl', category: 'upper', equipment: 'dumbbell' },
  { name: 'Tricep Pushdown', category: 'upper', equipment: 'cable' },
  { name: 'Lateral Raise', category: 'upper', equipment: 'dumbbell' },
  { name: 'Push-ups', category: 'upper', equipment: 'bodyweight' },
  { name: 'Pike Push-ups', category: 'upper', equipment: 'bodyweight' },
  { name: 'Dips', category: 'upper', equipment: 'bodyweight' },
  { name: 'Face Pull', category: 'upper', equipment: 'cable' },
  // Lower
  { name: 'Hack Squat', category: 'lower', equipment: 'machine' },
  { name: 'Back Squat', category: 'lower', equipment: 'barbell' },
  { name: 'Bulgarian Split Squat', category: 'lower', equipment: 'dumbbell' },
  { name: 'Stiff-Leg Deadlift', category: 'lower', equipment: 'barbell' },
  { name: 'Deadlift', category: 'lower', equipment: 'barbell' },
  { name: 'Leg Curl', category: 'lower', equipment: 'machine' },
  { name: 'Leg Press', category: 'lower', equipment: 'machine' },
  { name: 'Leg Extension', category: 'lower', equipment: 'machine' },
  { name: 'Standing Calf Raise', category: 'lower', equipment: 'machine' },
  { name: 'KB Goblet Squat', category: 'lower', equipment: 'kettlebell' },
  { name: 'KB Reverse Lunge', category: 'lower', equipment: 'kettlebell' },
  { name: 'Glute Bridge', category: 'lower', equipment: 'bodyweight' },
  { name: 'Single-Leg Glute Bridge', category: 'lower', equipment: 'bodyweight' },
  { name: 'Walking Lunge', category: 'lower', equipment: 'dumbbell' },
  // Core
  { name: 'Lying Leg Lift', category: 'core', equipment: 'bodyweight' },
  { name: 'Plank', category: 'core', equipment: 'bodyweight' },
  { name: 'Hanging Knee Raise', category: 'core', equipment: 'bodyweight' },
  { name: 'Cable Crunch', category: 'core', equipment: 'cable' },
  { name: 'Russian Twist', category: 'core', equipment: 'bodyweight' },
  { name: 'Ab Wheel Rollout', category: 'core', equipment: 'other' },
  // Cardio
  { name: 'Treadmill Run', category: 'cardio', equipment: 'machine' },
  { name: 'Outdoor Run', category: 'cardio', equipment: 'none' },
  { name: 'Walk', category: 'cardio', equipment: 'none' },
  { name: 'Cycling', category: 'cardio', equipment: 'bike' },
  { name: 'Rowing Machine', category: 'cardio', equipment: 'machine' },
  { name: 'Elliptical', category: 'cardio', equipment: 'machine' },
];
